name: citygml
services:
  threedfier:
    build:
      context: ./packages/threed_fier_package/
      dockerfile: Dockerfile
  bacalau_pipeline:
    build:
      context: ./packages/bacalhau_pipeline/
      dockerfile: Dockerfile.bacalhau

