FROM ghcr.io/bacalhau-project/bacalhau:latest 

#CMD [ "/bin/sh", "-c", "mkdir /app" ] 
WORKDIR /app
COPY ./run_bacalhau.sh /app/run_bacalhau.sh

RUN sudo chown root /bin/sh

CMD ["/bin/sh", "-c", "chmod ", "+x"  , "/app/run_bacalhau.sh" ]

ENTRYPOINT [ "/bin/sh " , "-c", "/app/run_bacalhau.sh" ]