name: surface_reconstruction
services:
  surface_reconstruction:
    build:
      context: ./packages/surface_reconstruction/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    
    
    volumes:
      - "./packages/surface_reconstruction/datas:/usr/src/app/reconstruction/datas/"
  
  georender:
    build:
      context: ./packages/georender
      dockerfile: Dockerfile
    x-develop:
      watch: 
        - action: sync
          path: ./packages/georender/
          target: /usr/src/app/georender/
          
    ports:
      - "8081:8081"
    
    volumes:
      - "./packages/georender/:/usr/src/app/georender/"

  py3dtiles:
    build:
      context: ./packages/py3dtiles/
      dockerfile: docker/Dockerfile
    
    ports:
      - "9080:9080"
    

  bacalhau:
    build:
      context: .
      dockerfile: Dockerfile.bacalhau

  threed_rendering:
    build:
      context: ./packages/3DTilesRendererJS
      dockerfile: docker/Dockerfile

  