name: Pipeline build passing
on:
     push:
         branches:
             - dev
             - main
job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: docker build for  georender
          run: docker compose build georender
        - name: docker build for surface_reconstruction pipeleine
          run: docker compose build surface_reconstruction

        - name: And finally for bacalhau pipeline
          run: docker compose build bacalhau
